name: Common Workflow Configuration

# This file contains shared configuration used by service-specific workflows
# It's not meant to be run directly

on:
  workflow_call:
    inputs:
      worker_dir:
        required: true
        type: string
        description: "The worker directory to deploy"
      environment:
        required: true
        type: string
        description: "The environment to deploy to (staging or production)"
      secret_names:
        required: false
        type: string
        description: "JSON array of secret names to pass to the worker"
        default: "[]"
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.worker_dir }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.5.2


      # Deploy the worker using Cloudflare Wrangler with service-specific secrets
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3.14.0
        # The environment variables are set dynamically in the previous step
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./workers/${{ inputs.worker_dir }}"
          packageManager: pnpm
          wranglerVersion: "3.114.0"
          env:
            secrets.SECRET1: ${{ secrets.SECRET1 }}
            secrets.SECRET1: ${{ secrets.SECRET2 }}
          secrets: |
            ${inputs.secret_names[0]}
            ${inputs.secret_names[1]}
          environment: ${{ inputs.environment }}
          command: ${{ format('deploy --env {0}', inputs.environment) }}
          secrets: ${{ steps.process-secrets.outputs.secrets-list }}