name: Deploy Agent Service

on:
  push:
    branches:
      - staging
      - main
    paths:
      - "workers/agent-service/**"
      - "shared/**"
  workflow_dispatch:
    inputs:
      force_deploy:
        description: "Force deploy this worker"
        required: false
        default: "false"
        type: boolean

jobs:
  deploy:
    # Skip if not workflow_dispatch and no relevant changes
    if: |
      github.event_name == 'workflow_dispatch' || 
      contains(github.event.head_commit.modified, 'workers/agent-service/') || 
      contains(github.event.head_commit.modified, 'shared/')
    uses: ./.github/workflows/common.yml
    with:
      worker_dir: "agent-service"
      environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
      secret_names: '["AGENT_SERVICE_PORTKEY_ENDPOINT", "AGENT_SERVICE_VERTEX_REGION"]'
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}