name: Deploy CF Worker

# Trigger the workflow on pushes to staging/main branches when worker code changes
# or manually via workflow_dispatch with optional parameters
on:
  push:
    branches:
      - staging
      - main
    paths:
      - "workers/**" # Only run when worker code changes
      - "shared/**" # Or when shared code used by workers changes
  workflow_dispatch:
    inputs:
      force_deploy:
        description: "Force deploy all workers"
        required: false
        default: "false"
        type: boolean
      specific_worker:
        description: "Deploy a specific worker (leave empty for automatic detection)"
        required: false
        type: string

jobs:
  # First job: Determine which workers need to be deployed
  scan-for-changes:
    name: Scan for worker code changes
    runs-on: ubuntu-latest
    outputs:
      worker-dirs: ${{ steps.changed-workers.outputs.worker-dirs }} # Output the list of workers to deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full git history needed to detect changes

      - name: Determine changed workers
        id: changed-workers
        run: |
          # Define all worker directories
          ALL_WORKER_DIRS='["agent-service", "api-entrypoint", "embedder-service", "screenshot-service", "search-service", "urlscan-service", "screenshot-backup-service", "trivialfilter-service"]'
          
          # Case 1: Manual trigger with force_deploy=true - deploy all workers
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.force_deploy }}" == "true" ]]; then
            echo "Force deploying all workers"
            WORKER_DIRS="$ALL_WORKER_DIRS"

          # Case 2: Manual trigger with specific worker - deploy only that worker
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.specific_worker }}" ]]; then
            echo "Deploying specific worker: ${{ github.event.inputs.specific_worker }}"
            WORKER_DIRS="[\"${{ github.event.inputs.specific_worker }}\"]"

          # Case 3: Automatic detection based on git changes
          else
            # Get list of files changed in this push
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            
            # If shared code changed, deploy all workers since they might depend on it
            if echo "$CHANGED_FILES" | grep -q "^shared/"; then
              echo "Changes detected in shared directory, deploying all workers"
              WORKER_DIRS="$ALL_WORKER_DIRS"
            else
              # Otherwise, only deploy workers with direct changes
              WORKER_CHANGES=$(echo "$CHANGED_FILES" | grep "^workers/" || true)
              if [[ -z "$WORKER_CHANGES" ]]; then
                echo "No worker changes detected"
                echo "worker-dirs=[]" >> $GITHUB_OUTPUT
                exit 0
              fi
              
              # Extract unique worker directory names and format as JSON array
              WORKER_DIRS=$(echo "$WORKER_CHANGES" | grep -o "workers/[^/]*" | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n") | map(select(length > 0))')
            fi
          fi

          # Set output variable and log results
          echo "worker-dirs=$WORKER_DIRS" >> $GITHUB_OUTPUT
          echo "Changed worker directories: $WORKER_DIRS"

  # Second job: Deploy each worker that needs updating
  deploy:
    name: Deploy worker to ${{  github.ref_name == 'main' && 'production' || github.ref_name }} (${{ matrix.worker-dir }})
    needs: scan-for-changes # Run after scan-for-changes job
    if: ${{ needs.scan-for-changes.outputs.worker-dirs != '[]' }} # Only run if there are workers to deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Set timeout to prevent hung deployments
    environment: ${{  github.ref_name == 'main' && 'production' || github.ref_name }} # Use 'production' for main branch, otherwise branch name
    strategy:
      matrix:
        # Create a job for each worker service
        worker-dir: ["agent-service", "api-entrypoint", "embedder-service", "screenshot-service", "search-service", "urlscan-service", "screenshot-backup-service", "trivialfilter-service"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.5.2 # Specify pnpm version for consistency

      # Check if this specific worker needs deployment
      - name: Check if worker has changes
        id: check-changes
        run: |
          CHANGED_WORKERS='${{ needs.scan-for-changes.outputs.worker-dirs }}'
          if echo $CHANGED_WORKERS | jq -e 'contains(["${{ matrix.worker-dir }}"])' > /dev/null; then
            echo "Worker ${{ matrix.worker-dir }} has changes, will deploy"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Worker ${{ matrix.worker-dir }} has no changes, skipping deployment"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      # Determine the correct secret name for this worker
      - name: Set secret name
        id: set-secret-name
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          # Convert worker-dir to secret name format (replace hyphens with underscores and uppercase)
          WORKER_NAME="${{ matrix.worker-dir }}"
          SECRET_NAME="${WORKER_NAME//-/_}"
          SECRET_NAME="${SECRET_NAME^^}_SECRETS"
          echo "secret-name=$SECRET_NAME" >> $GITHUB_OUTPUT
          echo "Using secret: $SECRET_NAME for worker: $WORKER_NAME"

      # Deploy the worker using Cloudflare Wrangler with service-specific secrets
      - name: Deploy to Cloudflare Workers
        if: steps.check-changes.outputs.has_changes == 'true' # Only deploy if this worker has changes
        uses: cloudflare/wrangler-action@v3.14.0
        env:
          # Include the service-specific secrets as environment variables
          # This will make them available to the worker during deployment
          ${{ steps.set-secret-name.outputs.secret-name }}: ${{ secrets[steps.set-secret-name.outputs.secret-name] }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./workers/${{ matrix.worker-dir }}" # Navigate to worker directory
          packageManager: pnpm # Use pnpm for package management
          wranglerVersion: "3.114.0" # Specify wrangler version
          environment: ${{  github.ref_name == 'main' && 'production' || github.ref_name }} # Set environment based on branch
          command: ${{ format('deploy --env {0}',  github.ref_name == 'main' && 'production' || github.ref_name) }} # Deploy command with environment
          secrets: ${{ steps.set-secret-name.outputs.secret-name }}
