name: Test Workflow

on:
  push:
    branches:
      - chore/test
      - main

# test2
jobs:
  test:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test job
        run: |
          echo "This is a test workflow"
          echo "Triggered by push to chore/test branch"